#! /bin/sh

xrandr --output eDP1 --scale 1x1 --mode 2560x1600 --output DP2 --mode 1024x768 --same-as eDP1 --scale 2.5x2.09

xrandr --output eDP1 --mode 2560x1600 --scale 1x1 --output DP2 --mode 1024x768 --scale 1x1 --left-of eDP1

xrandr --output eDP1 --mode 1280x800 --output VGA --mode 1024x768 --right-of eDP1 
